# Generated by Django 3.0.8 on 2021-02-15 12:53

from django.db import migrations, models
import utils.allowed_files


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20201227_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/', validators=[utils.allowed_files.validate_file_extension])),
            ],
        ),
        migrations.AlterField(
            model_name='online',
            name='file',
            field=models.FileField(upload_to='online/', validators=[utils.allowed_files.validate_file_extension]),
        ),
    ]
