# Generated by Django 3.0.8 on 2021-03-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210215_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offline',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='online',
            name='file',
            field=models.FileField(upload_to='online/'),
        ),
    ]
